name: Continuous Integration

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  lint-and-test-3-11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"
    - run: pip install .[dev,pymc3]
    - name: Formatting
      run: ruff format --check
    - name: Linters
      run: ruff check
    - name: Tests
      run: pytest tests -r a

  lint-and-test-post-3-11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - run: pip install .[dev]
    - name: Formatting
      run: ruff format --check
    - name: Linters
      run: ruff check
    - name: Tests
      run: pytest tests -r a
